export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.', 'BANCO FIBRA S.A.',
  'NU PAGAMENTOS - IP'
];

export const NOTIF_SOUND = '/som.mp3';

export const CONFIRMACOES = [
  "sim, sou eu!",
  "isso simm!!",
  "simmmmm",
  "opaaa sou eu sim",
  "sim, participei sim!",
  "sim, eu mesmo!",
  "simm, fui eu",
  "sim sim, sou eu",
  "issoo, eu!!",
  "sim, claro!!",
  "siim, eu tava la",
  "com certeza",
  "sou eu sim!",
  "sim, pode crer",
  "simmmm, eu!",
  "isso, sou eu",
  "sim, tava na live",
  "simm!",
  "sim, opa sou eu",
  "sim sim sim!",
  "claro, sou eu",
  "simm, isso ai",
  "sim, participei",
  "isso memo sou eu",
  "opa, sim sou eu",
  "isso ai, eu!",
  "com certeza sou eu",
  "sim, tava sim",
  "sim, valeu",
  "sim, eu mesmo!",
];

export const RESPOSTAS_COMUNS = [
  "chegou sim","sim valeu","vlw msm","Deus te abençoe","mt obrigado",
  "obrigadão","só gratidão","Deus te abençoe mano","que isso fera, valeu mesmo",
  "só sucesso chegou sim","pode crer","tmj sempre","pode pá",
  "n esperava por essa","vlw de boa","que isso manso",  "Muito obrigado",
  "Gratidão infinita","Agradeço demais","valeu","brigadão","Paz e bençãos",
  "n to acreditando kkkk","ce é brabo demais","nunca duvidei","parceiro vc é fera",
  "top demais veiooo","obrigado de coração","nunca vi isso, achei que era brincadeira",
  "valeu demais","que isso fera","só sucesso",
  "Obrigado demais","cê é foda to de cara","cê ta maluco tu mandou mesmo vei",
  "mano do céu to chorando",
  "voce nao imagina o quanto eu tava precisando agora vai dar pra pagar aquela conta q não deixava eu dormir",
  "era oq tava precisando cara ....... caralho!",
  "salvou minha semana patrão infinitos obgd ai","obrigado demais, isso vai ajudar muito",
  "n acredito que caiu na conta","pode parar de ser bom demais kkk",
  "vlw mesmo, tava no sufoco","Deus te pague tudo mano","caralho real msm? valeu!",
  "que tipo de anjo é vc","obrigadão, paga meu lanche da semana","só gratidão mesmo",
  "cara ce salvou meu dia","to sem palavras, obg",
  "manda bem demais vei","Deus te pague",
];

export const RESPOSTAS_5000 = [
  "meu deus mano é serio isso? salvou demais achei que tava brincando",
  "putz mano voce salvou minha vida",
  "esse valor vai fazer diferença pra mim cara muito obg",
  "cego de pedra aqui tu mandou mesmo piá KAKAKAKA",
  "cara eu tava prestes a ser despejado eu nao to nem acreditando q tu mandou mesmo vou poder quitar os atrasado amanha",
  "obrigado mano isso muda tudo aqui em casa",
  "to tremendo, 5k caiu de verdade",
  "não esperava nada assim, valeu demais",
  "vc é diferenciado mesmo, Deus te abençoe",
  "isso aqui paga minhas contas do mês",
  "caramba 5 mil?? tu é brabo",
  "salvou minha família essa semana",
  "to chorando mano, obrigado",
  "pode crer que vício em bondade",
  "n acredito que caiu 5k",
  "Deus te pague infinito",
  "mano ce é fora do normal",
  "obrigado de coração mesmo",
  "nunca pensei que ia receber isso",
  "tu é luz na minha vida",
];