export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.', 'BANCO FIBRA S.A.',
  'NU PAGAMENTOS - IP'
];

export const NOTIF_SOUND = '/som.mp3';